// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:1061453350021:web:d4518c213d094381fad5ec',
    messagingSenderId: '1061453350021',
    projectId: 'login-and-signin-9631d',
    authDomain: 'login-and-signin-9631d.firebaseapp.com',
    storageBucket: 'login-and-signin-9631d.appspot.com',
    measurementId: 'G-852EDPLWVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:1061453350021:android:d1733a10ace6e744fad5ec',
    messagingSenderId: '1061453350021',
    projectId: 'login-and-signin-9631d',
    storageBucket: 'login-and-signin-9631d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:1061453350021:ios:006b272e0f2a4160fad5ec',
    messagingSenderId: '1061453350021',
    projectId: 'login-and-signin-9631d',
    storageBucket: 'login-and-signin-9631d.appspot.com',
    iosClientId: '1061453350021-u9lmt10fqj0mqjufmnokd6rq2pfp9n8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:1061453350021:ios:006b272e0f2a4160fad5ec',
    messagingSenderId: '1061453350021',
    projectId: 'login-and-signin-9631d',
    storageBucket: 'login-and-signin-9631d.appspot.com',
    iosClientId: '1061453350021-u9lmt10fqj0mqjufmnokd6rq2pfp9n8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndSignup',
  );
}
